engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
      
ratings:
  paths:
  - "src/**"
  
## exclude src folder from codeclimate
exclude_paths:
- "build/**"
- "test/"