engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
      
ratings:
  paths:
  - build/**
  
## exclude src folder from codeclimate
exclude_paths:
- "build/"
- "test/"